config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :rounds, only: [:index, :show] do
        resources :tip, only: [:index, :show, :new, :create, :edit]
  end

  # This is for the one user to many tips
  resource :user do
        resources :tip
  end

  resources :leagues, only: [:index]

  root to: 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wadda Bewdy</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>

      <%= google_webfonts_init({
        google: ['Roboto Slab', 'Roboto', 'Montserrat', 'Kaushan Script', 'Droid Serif']
      }) %>
  </head>
  <body id="page-top" class="index">
  <!-- Navigation -->
  <%= render 'shared/nav' %>

  <!-- Sidebar -->
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-inverse nav-sidebar montserrat-font">
          <li>
            <%= link_to 'Rounds Home', rounds_path %>
          </li>
          <li>
            <%= link_to 'My Tips', user_tip_index_path %>
          </li>
          <li>
            <%= link_to 'League Results', leagues_path %>
          </li>
        </ul>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <%= render 'shared/flash' %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WaddaBewdy</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>

      <%= google_webfonts_init({
        google: ['Roboto Slab', 'Roboto', 'Montserrat', 'Kaushan Script', 'Droid Serif']
      }) %>
  </head>
  <body id="page-top" class="index">
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Wadda Bewdy</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#">Rules</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#">How to Play</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    <li>
                        <% if user_signed_in? %>
                            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
                        <% else %>
                            <%= link_to 'Login', new_user_session_path %>
                      <% end %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <%= yield %>

  </body>
</html>